### PR TITLE
Add: Channel sign and API sign method for client and update Readme

### PR DESCRIPTION
**Pull request by gauravtiwari**
Hey @FZambia 

Added channel sign and api method into Ruby client. Updated Readme with instructions to sign channels with a specific Rails example. 

Please review and merge. 

Cheers

### CODE REVIEW

**Comment by gauravtiwari** [comment]
@FZambia looks like authentication error, Please check.

**Comment by FZambia** [comment]
@gauravtiwari thanks a lot for improvements! I think travis builds failed because you changed `sign` method (it not using `project_key` anymore) while `process` method in this line https://github.com/centrifugal/centrifuge-ruby/blob/master/lib/centrifuge/builder.rb#L13 calls it with just a data.

```
client.sign(body[:data])
```

I think if you pass "#{project_key}#{data}" then everything will work. Unfortunately I am not skilled in Ruby, @arrowcircle, could you help us here?

**Comment by gauravtiwari** [comment]
Sure, let me fix this.

**Comment by gauravtiwari** [comment]
@FZambia I think should work now (all tests are passing), once travis builds are finished. (Travis-CI is down at the moment).

**Comment by FZambia** [comment]
`generate_api_sign` does the same as `sign`. I don't think we should add new method with the same functionality.

**Comment by gauravtiwari** [comment]
Okay I see. `Cent` python lib has this method https://github.com/centrifugal/cent/blob/master/cent/core.py#L59. 

``` python
def generate_api_sign(project_secret, project_key, encoded_data):
    """
    Generate HMAC sign for api request
    """
    sign = hmac.new(six.b(str(project_secret)), digestmod=sha256)
    sign.update(six.b(project_key))
    sign.update(encoded_data)
    return sign.hexdigest()
```

**Comment by gauravtiwari** [comment]
But I see your point, we could use the same sign method to generate api_sign. Just need to pass the data, like so: `client.sign(data)`

**Comment by gauravtiwari** [comment]
@FZambia I have removed the duplicate sign method and improved docs. See here: https://github.com/gauravtiwari/centrifuge-ruby#channel-sign-token-generation , plus https://github.com/gauravtiwari/centrifuge-ruby#api-request-sign

**Comment by FZambia** [comment]
Great, thank you very much for your work here!

**Comment by arrowcircle** [comment]
@FZambia should I release new version of gem?

**Comment by FZambia** [comment]
@arrowcircle I think it would be nice, I also started work in separate branch (https://github.com/centrifugal/centrifuge-ruby/tree/single_project) - I am planning to drop support for multiple projects registered in next release of Centrifugo (see https://github.com/centrifugal/centrifugo/issues/33).  There are some refactoring to get rid of `project_key`. Will appreciate your point on this change.

**Comment by gauravtiwari** [comment]
@FZambia I think that's the ideal way for Centrifugo to work. In most cases, people would be using this for a single project in production environment so, it doesn't make sense to support multiple projects, which brings additional complexity - scaling, configuration etc. 

Have you seen a gem called [Slanger](https://github.com/stevegraham/slanger). It's based on Pusher protocol and uses all Pusher libraries except the server, and the server only work for a single project.

**Comment by FZambia** [comment]
@gauravtiwari thanks for feedback, I have not seen Slanger before - looks great, and being compatible with pusher protocol is a great win in terms of client libraries for various languages.

**Comment by arrowcircle** [comment]
@gauravtiwari If you are looking for pusher backend look at https://github.com/edgurgel/poxa

**Comment by gauravtiwari** [comment]
@arrowcircle It's very similar to Slanger, although written in Elixer. I have used Slanger in production and it works pretty good. 

@FZambia May be we can extend Centrifugo client side libraries - borrow some ideas from Pusher? I noticed couple of bugs that I will report as a separate issue.

**Comment by FZambia** [comment]
@gauravtiwari depends on what you want to borrow

**Pull request merged**
